### ISSUE TITLE
[FEATURE] Showing player count in server

### ISSUE THREAD

**Issue by Programmer-Timmy** [ThePhaseCat/phases-discord-rich-presence#3]
**Describe the bug**
When playing on a server, the player count displays as 1 of 1, even though there are more players and more player slots available.

**Expected behavior**
The player count should show the correct number of players and available slots.

**Screenshots**
![image](https://github.com/user-attachments/assets/49912c46-8341-4a9d-bd29-c1237a9919a8)

**Comment by ThePhaseCat** [comment]
hi! this is the result of me passing `1` to a setting related to party size and party max size in the presence system i use. there seems to be no way of getting the amount of people in a server client-side (at least, from my digging i wasn't able to find any way of doing it). i've removed this code to set these values, thereby removing this from ever showing up in the presence.

sorry :(

**Comment by Programmer-Timmy** [comment]
No worries. Maybe I can find something for you

**Comment by Programmer-Timmy** [comment]
ClientPlayNetHandler#getOnlinePlayers will give you information about online players. This is the same data that is shown in the tab menu.

Found this

**Comment by ThePhaseCat** [comment]
unfortunately that's for forge, not fabric :(

**Comment by Programmer-Timmy** [comment]
Sandes

**Comment by ThePhaseCat** [comment]
reopening this because i figured out a way to get how many players are currently on the server you're on, already coded and will be arriving with version 1.5!

**Comment by ThePhaseCat** [comment]
(also renamed this because it's now a feature lol)

**Comment by ThePhaseCat** [comment]
This feature was added with version 1.5, which has been released! As such, this pull request will be closed! Thank you for bringing this bug but now feature to my attention!
